%%{init: {
    'theme': 'base',
    'fontFamily' : 'verdana',
    'fontSize' : '10'
}}%%

%% https://mermaid.js.org/config/theming.html
%% default, neutral, dark, forest, base

%% @paulorcf - 04.2024 - v1

mindmap
    root((Fundamentos LLM))
        id[Básico]
        ::icon(fa fa-book)
        :::urgent large
            Matemática para aprendizado de máquina
                ::icon(fas fa-wrench)
                Álgebra Linear
                Cálculo
                Probabilidade e estatística
            Python para aprendizado de máquina
                ::icon(fas fa-wrench)
                Básico de Python
                Bibliotecas de Data Science
                Pré-processamento de dados
                Bibliotecas de aprendizado de máquina
        id{{Intermediário}}
        ::icon(fa fa-book)
        :::urgent large
            {{Redes Neurais}}
                ::icon(fas fa-wrench)
                Fundamentos
                Treinamento e Optimização
                "Overfitting"
                Implementação Multilayer Perceptron

        id(Avançado)
        ::icon(fa fa-book)
        :::urgent large
            {{Processamento de linguagem natural}}
                ::icon(fas fa-wrench)
                Pré-processamento de texto
                Técnicas de extração de característica (Feature)
                Embeddings de palavras
                Rede neural recorrente